import discord
from discord.ext import commands
import os
import asyncio
import io
import random
from concurrent.futures import ThreadPoolExecutor
from huggingface_hub import InferenceClient
from sounds import SOUNDS

DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")
HF_TOKEN = os.getenv("HF_TOKEN")

SOUND_CHANNEL_ID = 1477710142425403523

image_client = InferenceClient(provider="hf-inference", api_key=HF_TOKEN)
chat_client = InferenceClient(api_key=HF_TOKEN)
executor = ThreadPoolExecutor()

intents = discord.Intents.default()
intents.message_content = True
bot = commands.Bot(command_prefix="!", intents=intents)


SIXTYSEVEN_GIFS = [
    "https://giphy.com/gifs/67-six-seven-john-chungus-08uBcURaMq6vA93TGc",
    "https://giphy.com/gifs/rigby-rigbycat-67-8rN9VXNb7dfU792YQt",
    "https://giphy.com/gifs/cat-nub-nubcat-TKa7fQzChHylCQ89to",
    "https://giphy.com/gifs/brainrot-67-hate-MKUOUJrFldIyi2hJyT",
    "https://giphy.com/gifs/argentina-vtuber-mialygosa-B4VWevk4w1a95oBHqv",
]

@bot.event
async def on_message(message):
    if message.author.bot:
        return
    if "67" in message.content:
        gif = random.choice(SIXTYSEVEN_GIFS)
        await message.channel.send(gif)
    await bot.process_commands(message)

async def play_sound(guild, sound_name):
    source = SOUNDS[sound_name]
    channel = guild.get_channel(SOUND_CHANNEL_ID)
    if channel is None:
        raise Exception("Voice channel not found!")
    vc = guild.voice_client
    if vc is None:
        vc = await channel.connect()
    elif vc.channel.id != SOUND_CHANNEL_ID:
        await vc.move_to(channel)
    if source.startswith("http"):
        audio = discord.FFmpegPCMAudio(source, before_options="-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5")
    else:
        audio = discord.FFmpegPCMAudio(source)
    vc.play(audio)

class SoundboardView(discord.ui.View):
    def __init__(self):
        super().__init__(timeout=None)
        for name in SOUNDS:
            self.add_item(SoundButton(name))

class SoundButton(discord.ui.Button):
    def __init__(self, sound_name):
        super().__init__(label=sound_name.title(), style=discord.ButtonStyle.primary, custom_id=f"sound_{sound_name}")

    async def callback(self, interaction: discord.Interaction):
        if interaction.guild.voice_client and interaction.guild.voice_client.is_playing():
            await interaction.response.send_message("⏳ Already playing a sound, wait!", ephemeral=True)
            return
        await interaction.response.defer(ephemeral=True)
        try:
            await play_sound(interaction.guild, self.label.lower())
            await interaction.followup.send(f"✅ Played **{self.label}**!", ephemeral=True)
        except Exception as e:
            await interaction.followup.send(f"❌ Failed: `{e}`", ephemeral=True)

@bot.tree.command(name="soundboard", description="Open the soundboard")
async def soundboard(interaction: discord.Interaction):
    embed = discord.Embed(
        title="🔊 Soundboard",
        description="Press a button to play a sound in the voice channel.",
        color=discord.Color.orange()
    )
    await interaction.response.send_message(embed=embed, view=SoundboardView())

@bot.tree.command(name="joinvoice", description="Make the bot join the voice channel")
async def joinvoice(interaction: discord.Interaction):
    channel = bot.get_channel(SOUND_CHANNEL_ID)
    if channel is None:
        await interaction.response.send_message("❌ Voice channel not found!", ephemeral=True)
        return
    if interaction.guild.voice_client:
        await interaction.response.send_message("✅ Already in the voice channel!", ephemeral=True)
        return
    await channel.connect()
    await interaction.response.send_message("✅ Joined the voice channel!", ephemeral=True)

def generate_image(prompt):
    image = image_client.text_to_image(prompt, model="black-forest-labs/FLUX.1-schnell")
    buf = io.BytesIO()
    image.save(buf, format="PNG")
    buf.seek(0)
    return buf

@bot.tree.command(name="imagine", description="Generate an AI image from a prompt")
async def imagine(interaction: discord.Interaction, prompt: str):
    await interaction.response.defer()
    try:
        loop = asyncio.get_event_loop()
        buf = await loop.run_in_executor(executor, generate_image, prompt)
        file = discord.File(fp=buf, filename="image.png")
        embed = discord.Embed(description=f"**{prompt}**", color=discord.Color.purple())
        embed.set_image(url="attachment://image.png")
        embed.set_footer(text="Generated by FLUX.1")
        await interaction.followup.send(embed=embed, file=file)
    except Exception as e:
        await interaction.followup.send(f"❌ Failed: `{e}`", ephemeral=True)

@bot.tree.command(name="ask", description="Ask an AI a question")
async def ask(interaction: discord.Interaction, prompt: str):
    await interaction.response.defer()
    try:
        result = chat_client.chat.completions.create(
            model="deepseek-ai/DeepSeek-V3-0324",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=1024
        )
        answer = result.choices[0].message.content
        embed = discord.Embed(description=f"**{prompt}**\n\n{answer}", color=discord.Color.blue())
        embed.set_footer(text="Powered by DeepSeek V3")
        await interaction.followup.send(embed=embed)
    except Exception as e:
        await interaction.followup.send(f"❌ Failed: `{e}`", ephemeral=True)

@bot.tree.command(name="coinflip", description="Flip a coin")
async def coinflip(interaction: discord.Interaction):
    await interaction.response.defer()
    suspense = ["🪙 Flipping the coin...", "🌀 It's spinning in the air...", "😮 Almost there..."]
    msg = await interaction.followup.send(suspense[0])
    await asyncio.sleep(1.2)
    await msg.edit(content=suspense[1])
    await asyncio.sleep(1.2)
    await msg.edit(content=suspense[2])
    await asyncio.sleep(1.2)
    result = random.choice(["Heads", "Tails"])
    emoji = "👑" if result == "Heads" else "✨"
    embed = discord.Embed(title=f"{emoji} {result}!", color=discord.Color.gold())
    await msg.edit(content=None, embed=embed)

@bot.event
async def on_ready():
    await bot.tree.sync()
    print(f"Logged in as {bot.user}")

bot.run(DISCORD_TOKEN)