import discord
from discord.ext import commands
import os
import asyncio
import aiohttp
import io

DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")
HF_TOKEN = os.getenv("HF_TOKEN")

API_URL = "https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-xl-base-1.0"

HEADERS = {
    "Authorization": f"Bearer {HF_TOKEN}"
}

intents = discord.Intents.default()
bot = commands.Bot(command_prefix="!", intents=intents)

@bot.tree.command(name="imagine", description="Generate an AI image from a prompt")
async def imagine(interaction: discord.Interaction, prompt: str):
    await interaction.response.defer()

    try:
        timeout = aiohttp.ClientTimeout(total=120)
        async with aiohttp.ClientSession(timeout=timeout) as session:
            async with session.post(API_URL, headers=HEADERS, json={"inputs": prompt}) as r:
                if r.status == 200:
                    image_data = await r.read()
                    file = discord.File(
                        fp=io.BytesIO(image_data),
                        filename="image.png"
                    )
                    embed = discord.Embed(
                        description=f"**{prompt}**",
                        color=discord.Color.purple()
                    )
                    embed.set_image(url="attachment://image.png")
                    embed.set_footer(text="Generated by Stable Diffusion XL")
                    await interaction.followup.send(embed=embed, file=file)
                elif r.status == 503:
                    await interaction.followup.send("⏳ Model is loading, try again in 20 seconds.", ephemeral=True)
                else:
                    text = await r.text()
                    await interaction.followup.send(f"❌ Error {r.status}: `{text}`", ephemeral=True)
    except asyncio.TimeoutError:
        await interaction.followup.send("⏱️ Timed out. Try again.", ephemeral=True)
    except Exception as e:
        await interaction.followup.send(f"❌ Something went wrong: `{e}`", ephemeral=True)

@bot.event
async def on_ready():
    await bot.tree.sync()
    print(f"Logged in as {bot.user}")

bot.run(DISCORD_TOKEN)