import discord
from discord.ext import commands
import os
import asyncio
import io
import random
from concurrent.futures import ThreadPoolExecutor
from huggingface_hub import InferenceClient

DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")
HF_TOKEN = os.getenv("HF_TOKEN")

image_client = InferenceClient(provider="hf-inference", api_key=HF_TOKEN)
chat_client = InferenceClient(api_key=HF_TOKEN)
executor = ThreadPoolExecutor()

intents = discord.Intents.default()
intents.message_content = True
bot = commands.Bot(command_prefix="!", intents=intents)

SIXTYSEVEN_GIFS = [
    "https://tenor.com/view/6-7-6-7-mason-67-kid-67-mason-67-meme-gif-14085771333654173149",
    "https://tenor.com/view/south-park-67-67-meme-67-kid-south-park-67-gif-5327133294253067463",
    "https://tenor.com/view/67-meme-six-seven-six-seven-67-kid-gif-18263820823886954909",
    "https://tenor.com/view/6-6-7-6-7-mason-67-kid-67-mason-gif-15019642513342783186",
    "https://tenor.com/view/67-67-kid-edit-analog-horror-phonk-gif-3349401281762803381",
]

@bot.event
async def on_message(message):
    if message.author.bot:
        return
    if "67" in message.content:
        gif = random.choice(SIXTYSEVEN_GIFS)
        await message.channel.send(gif)
    await bot.process_commands(message)

def generate_image(prompt):
    image = image_client.text_to_image(prompt, model="black-forest-labs/FLUX.1-schnell")
    buf = io.BytesIO()
    image.save(buf, format="PNG")
    buf.seek(0)
    return buf

@bot.tree.command(name="imagine", description="Generate an AI image from a prompt")
async def imagine(interaction: discord.Interaction, prompt: str):
    await interaction.response.defer()
    try:
        loop = asyncio.get_event_loop()
        buf = await loop.run_in_executor(executor, generate_image, prompt)
        file = discord.File(fp=buf, filename="image.png")
        embed = discord.Embed(description=f"**{prompt}**", color=discord.Color.purple())
        embed.set_image(url="attachment://image.png")
        embed.set_footer(text="Generated by FALIX BOT")
        await interaction.followup.send(embed=embed, file=file)
    except Exception as e:
        await interaction.followup.send(f"❌ Failed: `{e}`", ephemeral=True)

@bot.tree.command(name="ask", description="Ask an AI a question")
async def ask(interaction: discord.Interaction, prompt: str):
    await interaction.response.defer()
    try:
        result = chat_client.chat.completions.create(
            model="deepseek-ai/DeepSeek-V3-0324",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=1024
        )
        answer = result.choices[0].message.content
        embed = discord.Embed(description=f"**{prompt}**\n\n{answer}", color=discord.Color.blue())
        embed.set_footer(text="Powered by FALIX BOT")
        await interaction.followup.send(embed=embed)
    except Exception as e:
        await interaction.followup.send(f"❌ Failed: `{e}`", ephemeral=True)

@bot.tree.command(name="coinflip", description="Flip a coin")
async def coinflip(interaction: discord.Interaction):
    await interaction.response.defer()
    suspense = ["🪙 Flipping the coin...", "🌀 It's spinning in the air...", "😮 Almost there..."]
    msg = await interaction.followup.send(suspense[0])
    await asyncio.sleep(1.2)
    await msg.edit(content=suspense[1])
    await asyncio.sleep(1.2)
    await msg.edit(content=suspense[2])
    await asyncio.sleep(1.2)
    result = random.choice(["Heads", "Tails"])
    emoji = "👑" if result == "Heads" else "✨"
    embed = discord.Embed(title=f"{emoji} {result}!", color=discord.Color.gold())
    await msg.edit(content=None, embed=embed)

@bot.event
async def on_ready():
    await bot.tree.sync()
    print(f"Logged in as {bot.user}")

bot.run(DISCORD_TOKEN)